services:
  server:
    image: server-image
    build: ./server
    environment:
      - DATABASE_URI=database
    ports:
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - ./server/.env
  client:
    image: client-image
    build: ./client
    ports:
      - "8080:8080"
  database: 
    image: mongo 
    ports:
      - "27017:27017"
